### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by DJaeger** [felixwoestmann/spickerrr#1]
How about publishing this app to the F-Droid store?

**Comment by LostInCoding** [comment]
Ich bin mir gerade sehr unsicher ob das funktionieren würde.
Zuerst müsste ich meine dependencies durchgehen und schauen ob ich dort irgendwo unfreie Software verwende.

**Comment by DJaeger** [comment]
Aus diesem Grund habe ich gefragt und nicht "gemacht" ;-)

P.S.: Ich habe im Wiki unter "Piraten-Software" auf deine Spickerrr-App geändert. :-)

**Comment by DJaeger** [comment]
Apache License, Version 2.0: 
 - Retrofit
 - OkHttp
 - FloatingActionButton
 - opencsv
 - Apache Commons Lang

MIT license
 - jsoup

Dann sind da noch die Support Libs, da bin ich mir nicht sicher, müsste man noch schauen, ich meine die sind aber auch i.O.

Im Travis YAML steht aber was von den Google Play Services, die gehen natürlich nicht.

**Comment by DJaeger** [comment]
Ansonsten mal
gradle -q dependencies your-app-project:dependencies
ausführen, was wirklich verwendet wird.

**Comment by DJaeger** [comment]
Ach, vergessen:
JUnit ist Eclipse Public License 1.0

**Comment by DJaeger** [comment]
JARs hab ich keine gesehen (auch wenn die vom gradle eingebunden werden ;-) )

**Comment by DJaeger** [comment]
Soweit mein Zwischenstand vom Handy aus

**Comment by DJaeger** [comment]
Spickerrr 2.1
Spickerrr 2.1 (Die Antragsapp für Parteitage der Piratenpartei) - https://f-droid.org/packages/de.piratentools.spickerrr
